// <auto-generated />
using System;
using GPBag.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GPBag.Data.Migrations
{
    [DbContext(typeof(GPContext))]
    [Migration("20221121150425_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("GPBag.Data.Models.BaggageGridModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BaggageReceived")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BaggageReturned")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bagsize")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bagtype")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfBoxes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RackNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaggageGridModel");
                });

            modelBuilder.Entity("GPBag.Data.Models.BaggageGridModelArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BaggageReceived")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BaggageReturned")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bagsize")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bagtype")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfBoxes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RackNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaggageGridModelArchive");
                });
#pragma warning restore 612, 618
        }
    }
}
